version: '3'

services:
    postgres:
        container_name: postgres
        build: ./database
        ports:
            - "5432:5432"    
        env_file: 
            ./database/.env                

    redis:
        container_name: redis
        restart:  on-failure
        image: redis
        ports:
            - "127.0.0.1:6379:6379"

    go:
        container_name: auth-service
        restart: on-failure
        build: ./auth-service
        ports:
            - "8080:8080"