version: '3'

services:
    postgres:
        container_name: workspace-users
        volumes:
            - db-data:/var/lib/postgresql/data
        env_file: 
            ./database/.env
        build: ./database
        ports:
            - "5432:5432"
        networks:
            workspacenet:
                ipv4_address:
                    172.28.1.1
    go:
        container_name: auth-service
        restart: on-failure
        build: ./auth-service
        ports:
            - "80:80"
        networks:
            workspacenet:
                ipv4_address: 172.28.1.2

networks:
    workspacenet:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16

volumes:
    db-data:
        driver: local