version: '3'

services:
    postgres:
        container_name: postgres
        image: postgres:latest  
        restart:  on-failure         
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    redis:
        image: redis
        container_name: redis
        restart:  on-failure

    auth:
        container_name: auth-service
        build: ./auth-service
        restart: on-failure
        ports:
            - "8080:8080"
        command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; npm start'

    #resource:
    #    container_name: resource-service
    #    restart: on-failure
    #    build: ./resource-service
    #    ports:
    #        - "8484:8484"       